"""CAGE EMPIRE Fighter Morale + Dynamic Meta-Fields System (Phase A — A1 + A10).

This module wires the two biggest "frozen field" gaps identified in
docs/FULL_BUILD_AUDIT.md:

  A1 — fighter_personality.morale (0-100, clamped to [10, 95]).
       The fight engine reads this column via _load_fighter_stats, but
       before this task NO system ever wrote to it after seed time.
       Wins, losses, injuries, title changes, camp completions, and
       time all left it frozen at the seed default of 50.

  A10 — fighters.* dynamic meta-fields (marketability, fan_friendliness,
       consistency, clutch_factor, promo_boost, injury_proneness,
       weight_cut_difficulty). Same problem: set at seed, never updated.

The fix is entirely event-bus-driven (CONVENTIONS §15.4 — no new inline
side effects added to resolve_next_fight or run_tick). The module
subscribes to 6 events:

  FIGHT_RESOLVED  → winner/loser morale swings + dynamic field bumps
  TITLE_CHANGED   → new champion +15, dethroned champion -15
  TICK_ADVANCED   → weekly drift toward 50, ring rust, win-streak
                    bonus, birthday-based aging of injury_proneness
                    and weight_cut_difficulty, injury-recovery morale
  CAMP_COMPLETED  → +3 morale (training went well)
  CAMP_INJURY     → -5 morale (training setback)
  FIGHT_CANCELLED → weight-cut miss: -5 (fighter who missed) / -3
                    (opponent). Subscribed for forward-compat; the
                    event is not yet published by app.py (Phase A5
                    wires news coverage and will publish it).

INJURY_CREATED / INJURY_RECOVERED are NOT subscribed directly because
the engine does not publish them. Instead:
  - New injuries are detected by scanning the `injuries` table for new
    rows for the resolved fight_id (inside the FIGHT_RESOLVED
    subscriber).
  - Recovered injuries are detected by scanning for
    `actual_return_date == current_date` (inside the TICK_ADVANCED
    subscriber).

VOICE LAYER (CONVENTIONS §14): the morale system produces NO player-
facing text. Morale is internal state that feeds the fight engine
(via _load_fighter_stats) and the descriptor snapshot (via
update_fighter_descriptor_snapshot). The morale descriptor itself is
generated by voice.py's PERSONALITY_DESCRIPTORS['morale'] when the
snapshot is refreshed. No raw numbers leak because morale writes no
prose of its own.

DESIGN LAW (CONVENTIONS §13):
  - Growth: morale drives fight performance (the beat engine loads it
    via _load_fighter_stats and uses it in pressure_response). A
    high-morale fighter gets a psychological lift; a low-morale
    fighter underperforms. The feedback loop is now CLOSED — wins
    boost morale → next fight gets a boost → more wins.
  - Conflict: losses hurt. KO losses hurt more. Losing streaks
    compound the pain. The "will he bounce back?" thread is now a
    real sim state, not just a storyline seed.
  - Anticipation: a champion with maxed morale creates the
    "complacency upset?" thread. A fighter on a skid creates the
    "must-win fight" thread. A prospect with rising morale creates
    the "is he the real deal?" thread.

USAGE:
  from morale import register_subscribers
  register_subscribers()  # call once at startup (UI App.__init__,
                          # test setup). Safe to call multiple times.
  # The morale system processes events automatically via the bus.
  # No need to call any function directly.
"""

import random
from datetime import datetime


# ----------------------------------------------------------------
# Constants
# ----------------------------------------------------------------

# Morale bounds — never 0 (broken fighter) or 100 (complacent). The
# brief mandates this clamp: a fighter at 0 morale would be a wreck,
# and a fighter at 100 would have nothing to chase. The [10, 95]
# band keeps morale impactful without breaking the sim.
MORALE_FLOOR = 10
MORALE_CEIL = 95

# Regression-to-mean anchor for weekly drift. Fighters naturally
# trend back toward "average mood" over time — the euphoria of a
# win fades, the sting of a loss softens. ±1 per week toward 50.
MORALE_MEAN = 50

# Days without a fight before "ring rust" kicks in. 90 days = ~3
# months. A fighter who hasn't fought in 3+ months loses -2 morale
# per week (forgotten by fans, questioning themselves).
RING_RUST_DAYS = 90

# Win-streak threshold for the weekly "riding high" bonus. A fighter
# on a 5+ win streak gains +1 morale per week (confidence compounds).
WIN_STREAK_HIGH = 5

# Losing-streak penalty parameters. -3 per consecutive loss beyond
# the first, capped at -9 (3 additional losses worth).
LOSS_STREAK_PENALTY_PER = -3
LOSS_STREAK_PENALTY_CAP = -9

# Winning-streak bonus parameters. +2 per consecutive win beyond the
# first, capped at +6 (3 additional wins worth).
WIN_STREAK_BONUS_PER = 2
WIN_STREAK_BONUS_CAP = 6

# Age thresholds for injury_proneness (+1/year over 30) and
# weight_cut_difficulty (+1/year over 32). The body wears down.
INJURY_PRONENESS_AGE_THRESHOLD = 30
WEIGHT_CUT_DIFFICULTY_AGE_THRESHOLD = 32

# Exciting-fight threshold: >10 beats in round 1 = exciting (the
# fight had early pace + action, not a feeling-out round).
EXCITING_FIGHT_BEAT_THRESHOLD = 10

# Cap for consistency growth (per the brief).
CONSISTENCY_CAP = 90
# Cap + floor for clutch_factor (per the brief).
CLUTCH_FACTOR_CAP = 90
CLUTCH_FACTOR_FLOOR = 20

# Promo_boost viral-post engagement threshold.
PROMO_BOOST_ENGAGEMENT_THRESHOLD = 50

# Personality field bounds (Stage5-Final). The schema CHECK is
# BETWEEN 0 AND 100, but we clamp tighter to [10, 95] per the brief
# — a 0-grit fighter would be a wreck, a 100-ambition fighter would
# be insatiable. Matches the morale [10, 95] clamp pattern.
PERSONALITY_FLOOR = 10
PERSONALITY_CEIL = 95

# Losing-streak / winning-streak thresholds for the weekly
# personality drift (Stage5-Final). Fighters on 3+ loss streaks get
# the "desperate to prove themselves" grit + ambition bumps; fighters
# on 5+ win streaks get the "comfortable" ambition drop.
LOSS_STREAK_GRIT_ONSET = 3
WIN_STREAK_COMFORT_ONSET = 5


# ----------------------------------------------------------------
# Internal helpers
# ----------------------------------------------------------------

def _clamp_morale(v):
    """Clamp a morale value to [MORALE_FLOOR, MORALE_CEIL]."""
    return max(MORALE_FLOOR, min(MORALE_CEIL, int(v)))


def _clamp_personality(v):
    """Clamp a personality field value to [PERSONALITY_FLOOR, PERSONALITY_CEIL].

    Stage5-Final — the 6 stale personality fields (grit, ambition,
    loyalty, resilience, travel_comfort, fatigue_tolerance) are clamped
    tighter than the schema's 0-100 CHECK. Preserves REAL values
    (travel_comfort is stored as REAL for 0.5 increments) by skipping
    the int() conversion when the input is a float.
    """
    if isinstance(v, float):
        return float(max(PERSONALITY_FLOOR, min(PERSONALITY_CEIL, v)))
    return max(PERSONALITY_FLOOR, min(PERSONALITY_CEIL, int(v)))


def _set_personality_field(conn, fighter_id, field, new_value,
                            update_snapshot=True):
    """Update a single fighter_personality field (Stage5-Final).

    Defensive — only allows the 6 personality fields owned by this
    task (grit, ambition, loyalty, resilience, travel_comfort,
    fatigue_tolerance). The whitelist prevents accidental writes to
    morale / aggression / composure (which have their own writers).

    Args:
        conn: sqlite3 connection (caller commits).
        fighter_id: the fighter to update.
        field: one of the 6 personality field names.
        new_value: the target value (will be clamped to [10, 95]).
        update_snapshot: if True (default), refresh the fighter's
            descriptor snapshot so the UI sees the new tier.
    """
    _ALLOWED = {
        "grit", "ambition", "loyalty", "resilience",
        "travel_comfort", "fatigue_tolerance",
    }
    if field not in _ALLOWED:
        return  # defensive — caller bug, refuse to write
    clamped = _clamp_personality(new_value)
    conn.execute(
        f"UPDATE fighter_personality SET {field}=? "
        f"WHERE fighter_id=?",
        (clamped, fighter_id),
    )
    if update_snapshot:
        _refresh_snapshot(conn, fighter_id)


def _get_morale(conn, fighter_id):
    """Return the fighter's current morale (default 50 if no row)."""
    row = conn.execute(
        "SELECT morale FROM fighter_personality WHERE fighter_id=?",
        (fighter_id,),
    ).fetchone()
    return row[0] if row and row[0] is not None else 50


def _set_morale(conn, fighter_id, new_morale, update_snapshot=True):
    """Update a fighter's morale (clamped to [10, 95]).

    Args:
        conn: sqlite3 connection (caller commits).
        fighter_id: the fighter whose morale to update.
        new_morale: the target morale value (will be clamped).
        update_snapshot: if True (default), refresh the fighter's
            descriptor snapshot so the UI sees the new morale tier
            immediately. Set False when batching many updates —
            the caller can refresh the snapshot once at the end.
    """
    clamped = _clamp_morale(new_morale)
    conn.execute(
        "UPDATE fighter_personality SET morale=? WHERE fighter_id=?",
        (clamped, fighter_id),
    )
    if update_snapshot:
        _refresh_snapshot(conn, fighter_id)


def _refresh_snapshot(conn, fighter_id):
    """Refresh the fighter's descriptor snapshot (lazy-import to avoid
    circular dependency with app.py)."""
    try:
        from app import update_fighter_descriptor_snapshot
        update_fighter_descriptor_snapshot(conn, fighter_id)
    except ImportError:
        pass  # defensive — app.py not available (headless test?)


def _streak(conn, fighter_id):
    """Return (win_streak, loss_streak) for the fighter (0,0 if no row)."""
    row = conn.execute(
        "SELECT win_streak, loss_streak FROM fighter_career WHERE fighter_id=?",
        (fighter_id,),
    ).fetchone()
    if not row:
        return 0, 0
    return row[0] or 0, row[1] or 0


def _days_since_last_fight(conn, fighter_id, current_date):
    """Days since the fighter's most recent fight (None if never fought)."""
    row = conn.execute(
        "SELECT MAX(event_date) FROM fight_history WHERE fighter_id=?",
        (fighter_id,),
    ).fetchone()
    if not row or not row[0]:
        return None
    try:
        last = datetime.strptime(row[0], "%Y-%m-%d")
        cur = datetime.strptime(current_date, "%Y-%m-%d")
        return (cur - last).days
    except (ValueError, TypeError):
        return None


def _is_weekly_tick(conn):
    """Return True if the current sim day is the last day of a sim week.

    The sim runs daily ticks; we treat days 7, 14, 21, ... as the
    weekly tick (end of week). This is the natural cadence for the
    morale drift / ring-rust / win-streak-bonus logic — applying
    them daily would shift morale too fast.
    """
    row = conn.execute(
        "SELECT simulation_clock.current_day "
        "FROM simulation_clock WHERE clock_id=1"
    ).fetchone()
    if not row or row[0] is None:
        return False
    return (row[0] % 7) == 0


# ----------------------------------------------------------------
# A1 — FIGHT_RESOLVED subscriber (morale + injury scan)
# ----------------------------------------------------------------

def _process_fight(conn, event):
    """Subscriber for FIGHT_RESOLVED — A1 morale + A10 dynamic fields.

    Sequence:
      1. Apply win/loss/draw morale changes to both fighters.
      2. Scan injuries table for new injuries for this fight_id and
         apply severity-scaled morale penalties (INJURY_CREATED
         surrogate — the engine doesn't publish INJURY_CREATED).
      3. Update A10 dynamic fields (marketability, fan_friendliness,
         consistency, clutch_factor, promo_boost).
      4. Refresh descriptor snapshots for both fighters (one pass).
    """
    fight_id = event.get('fight_id')
    if fight_id is None:
        return

    winner_id = event.get('winner_id')
    loser_id = event.get('loser_id')
    a_id = event.get('fighter_a_id')
    b_id = event.get('fighter_b_id')
    result_type = (event.get('result_type') or '').lower()
    is_title_fight = bool(event.get('is_title_fight'))
    title_changed = bool(event.get('title_changed'))

    # --- A1.1 — morale for fight outcome ---
    if result_type == 'draw' or winner_id is None:
        # Draw: +1 both (moral victory for the underdog).
        for fid in (a_id, b_id):
            if fid is None:
                continue
            m = _get_morale(conn, fid)
            _set_morale(conn, fid, m + 1, update_snapshot=False)
    else:
        # Winner base: +5 (or +15 for title win).
        if is_title_fight and title_changed:
            win_base = 15
        else:
            win_base = 5
        # Winning-streak bonus: +2 per consecutive win beyond the
        # first, capped at +6. The streak counter has already been
        # incremented by resolve_next_fight (side effect runs before
        # the event is published), so w_streak reflects the post-
        # fight streak.
        w_streak, _ = _streak(conn, winner_id)
        win_bonus = min(WIN_STREAK_BONUS_CAP,
                        max(0, w_streak - 1) * WIN_STREAK_BONUS_PER)
        m = _get_morale(conn, winner_id)
        _set_morale(conn, winner_id,
                    m + win_base + win_bonus, update_snapshot=False)

        # Loser base: -5 (KO/TKO: -10, submission: -8).
        if result_type in ('ko_tko', 'ko', 'tko'):
            loss_base = -10
        elif result_type == 'submission':
            loss_base = -8
        else:
            loss_base = -5
        # Losing-streak modifier: -3 per consecutive loss beyond the
        # first, capped at -9.
        _, l_streak = _streak(conn, loser_id)
        loss_penalty = max(LOSS_STREAK_PENALTY_CAP,
                           LOSS_STREAK_PENALTY_PER * max(0, l_streak - 1))
        m = _get_morale(conn, loser_id)
        _set_morale(conn, loser_id,
                    m + loss_base + loss_penalty, update_snapshot=False)

    # --- A1.2 — injury morale penalty (INJURY_CREATED surrogate) ---
    # The engine creates injuries via _check_post_fight_injuries just
    # before publishing FIGHT_RESOLVED. We scan the injuries table for
    # new rows tied to this fight and apply -1.0 morale per severity
    # point, capped at -10 per injury.
    inj_rows = conn.execute(
        "SELECT fighter_id, severity FROM injuries WHERE fight_id=?",
        (fight_id,),
    ).fetchall()
    for inj_fighter_id, sev in inj_rows:
        if inj_fighter_id is None:
            continue
        severity = sev if sev is not None else 5
        penalty = -min(10, int(severity * 1.0))
        m = _get_morale(conn, inj_fighter_id)
        _set_morale(conn, inj_fighter_id, m + penalty, update_snapshot=False)

    # --- A10 — dynamic meta-fields on the fighters table ---
    _update_fight_dynamic_fields(
        conn, fight_id, winner_id, loser_id, a_id, b_id,
        result_type, is_title_fight, title_changed,
    )

    # --- Stage5-Final — stale personality fields (grit, ambition,
    # resilience, travel_comfort) on FIGHT_RESOLVED ---
    _update_fight_personality_fields(
        conn, fight_id, winner_id, loser_id, a_id, b_id,
        result_type, is_title_fight, title_changed,
    )

    # --- Refresh descriptor snapshots for both fighters (one pass) ---
    # Done last so the snapshot reflects both the morale change AND
    # any dynamic-field changes (which feed the fighter_data dict).
    for fid in (a_id, b_id):
        if fid is None:
            continue
        _refresh_snapshot(conn, fid)


def _update_fight_dynamic_fields(conn, fight_id, winner_id, loser_id,
                                  a_id, b_id, result_type,
                                  is_title_fight, title_changed):
    """Update fighters.* columns based on a resolved fight (A10).

    Per the brief:
      marketability: +2 per win, +5 per title win, -1 per loss,
                     -10 per suspension (suspensions not yet
                     implemented — reserved).
      fan_friendliness: +1 per KO/submission win, -1 per boring
                        decision loss, +2 per exciting fight
                        (>10 beats in round 1).
      consistency: +0.5 per fight fought (cap at 90, floor at seed
                   value — we only increase, so the floor is
                   naturally maintained).
      clutch_factor: +2 if win in title fight, -2 if loss in title
                     fight (cap 90, floor 20).
      promo_boost: +1 per social post with engagement > 50
                   (counted between previous fight and this one).
    """
    is_finish = result_type in ('ko_tko', 'ko', 'tko', 'submission')

    # Determine "exciting fight" — >10 beats in round 1.
    exciting = False
    if fight_id is not None:
        row = conn.execute(
            "SELECT COUNT(*) FROM fight_beats "
            "WHERE fight_id=? AND round_number=1",
            (fight_id,),
        ).fetchone()
        if row and row[0] > EXCITING_FIGHT_BEAT_THRESHOLD:
            exciting = True

    # ---- marketability ----
    if winner_id is not None:
        mkt = conn.execute(
            "SELECT marketability FROM fighters WHERE fighter_id=?",
            (winner_id,),
        ).fetchone()
        if mkt:
            if is_title_fight and title_changed:
                bump = 5
            elif is_title_fight:
                bump = 3  # title defense win (not a title change)
            else:
                bump = 2
            new_mkt = min(100, (mkt[0] if mkt[0] is not None else 50) + bump)
            conn.execute(
                "UPDATE fighters SET marketability=?, "
                "updated_at=CURRENT_TIMESTAMP WHERE fighter_id=?",
                (new_mkt, winner_id),
            )
    if loser_id is not None:
        mkt = conn.execute(
            "SELECT marketability FROM fighters WHERE fighter_id=?",
            (loser_id,),
        ).fetchone()
        if mkt:
            new_mkt = max(0, (mkt[0] if mkt[0] is not None else 50) - 1)
            conn.execute(
                "UPDATE fighters SET marketability=?, "
                "updated_at=CURRENT_TIMESTAMP WHERE fighter_id=?",
                (new_mkt, loser_id),
            )

    # ---- fan_friendliness ----
    if winner_id is not None:
        ff = conn.execute(
            "SELECT fan_friendliness FROM fighters WHERE fighter_id=?",
            (winner_id,),
        ).fetchone()
        if ff:
            bump = 0
            if is_finish:
                bump += 1   # KO/submission win = exciting for fans
            if exciting:
                bump += 2   # bonus for being in an exciting fight
            new_ff = min(100, max(0,
                (ff[0] if ff[0] is not None else 50) + bump))
            conn.execute(
                "UPDATE fighters SET fan_friendliness=?, "
                "updated_at=CURRENT_TIMESTAMP WHERE fighter_id=?",
                (new_ff, winner_id),
            )
    if loser_id is not None:
        ff = conn.execute(
            "SELECT fan_friendliness FROM fighters WHERE fighter_id=?",
            (loser_id,),
        ).fetchone()
        if ff:
            bump = 0
            if not is_finish and not exciting:
                bump -= 1   # boring decision loss
            if exciting:
                bump += 2   # bonus for being in an exciting fight
            new_ff = min(100, max(0,
                (ff[0] if ff[0] is not None else 50) + bump))
            conn.execute(
                "UPDATE fighters SET fan_friendliness=?, "
                "updated_at=CURRENT_TIMESTAMP WHERE fighter_id=?",
                (new_ff, loser_id),
            )

    # ---- consistency: +0.5 per fight fought (cap 90) ----
    # SQLite INTEGER column accepts REAL values (NUMERIC affinity),
    # so +0.5 writes 50.5, 51.0, 51.5, ... naturally. The cap is 90.
    for fid in (a_id, b_id):
        if fid is None:
            continue
        row = conn.execute(
            "SELECT consistency FROM fighters WHERE fighter_id=?",
            (fid,),
        ).fetchone()
        if not row:
            continue
        cur_cons = row[0] if row[0] is not None else 50
        new_cons = min(float(CONSISTENCY_CAP), cur_cons + 0.5)
        if new_cons != cur_cons:
            conn.execute(
                "UPDATE fighters SET consistency=?, "
                "updated_at=CURRENT_TIMESTAMP WHERE fighter_id=?",
                (new_cons, fid),
            )

    # ---- clutch_factor: +2 title-fight win, -2 title-fight loss ----
    if is_title_fight:
        for fid, delta in ((winner_id, +2), (loser_id, -2)):
            if fid is None:
                continue
            row = conn.execute(
                "SELECT clutch_factor FROM fighters WHERE fighter_id=?",
                (fid,),
            ).fetchone()
            if not row:
                continue
            cur_cf = row[0] if row[0] is not None else 50
            new_cf = max(CLUTCH_FACTOR_FLOOR,
                         min(CLUTCH_FACTOR_CAP, cur_cf + delta))
            if new_cf != cur_cf:
                conn.execute(
                    "UPDATE fighters SET clutch_factor=?, "
                    "updated_at=CURRENT_TIMESTAMP WHERE fighter_id=?",
                    (new_cf, fid),
                )

    # ---- promo_boost: +1 per social post with engagement > 50 ----
    # Count viral posts between the fighter's previous fight and this
    # one. This is a per-fight window so the boost accumulates over a
    # career (each fight picks up the viral posts since the last one).
    for fid in (a_id, b_id):
        if fid is None or fight_id is None:
            continue
        row = conn.execute(
            "SELECT promo_boost FROM fighters WHERE fighter_id=?",
            (fid,),
        ).fetchone()
        if not row:
            continue
        cur_pb = row[0] if row[0] is not None else 0

        # Previous fight date (before this one) — used as the lower
        # bound on the post_date window.
        prev_row = conn.execute(
            "SELECT MAX(event_date) FROM fight_history "
            "WHERE fighter_id=? AND fight_id <> ?",
            (fid, fight_id),
        ).fetchone()
        since_date = prev_row[0] if prev_row and prev_row[0] else '1970-01-01'

        # This fight's date — upper bound on the post_date window.
        fight_date_row = conn.execute(
            "SELECT event_date FROM fight_history "
            "WHERE fighter_id=? AND fight_id=? "
            "ORDER BY event_date DESC LIMIT 1",
            (fid, fight_id),
        ).fetchone()
        if not fight_date_row:
            continue
        fight_date = fight_date_row[0]

        n_viral = conn.execute(
            "SELECT COUNT(*) FROM social_posts "
            "WHERE fighter_id=? AND engagement > ? "
            "AND post_date > ? AND post_date <= ?",
            (fid, PROMO_BOOST_ENGAGEMENT_THRESHOLD,
             since_date, fight_date),
        ).fetchone()[0]
        if n_viral > 0:
            new_pb = max(-100, min(100, cur_pb + n_viral))
            if new_pb != cur_pb:
                conn.execute(
                    "UPDATE fighters SET promo_boost=?, "
                    "updated_at=CURRENT_TIMESTAMP WHERE fighter_id=?",
                    (new_pb, fid),
                )


# ----------------------------------------------------------------
# Stage5-Final — stale personality field updates (FIGHT_RESOLVED)
# ----------------------------------------------------------------

def _update_fight_personality_fields(conn, fight_id, winner_id, loser_id,
                                      a_id, b_id, result_type,
                                      is_title_fight, title_changed):
    """Update fighter_personality stale fields on FIGHT_RESOLVED.

    Per the brief (Stage5-Final):
      - Winner: ambition -1 if was champion (satiated), +1 if underdog
        win (hungry for more). The two are mutually exclusive — a
        champion defending is never the underdog, and an underdog
        winning the belt is satiated (just achieved the dream).
      - Loser: grit +1 (adversity builds grit), resilience +1
        (bouncing back).
      - Loser by KO/TKO: grit +2 (real adversity), resilience -1
        (the chin cracks confidence — the fighter questions whether
        they can take a shot anymore). Overrides the standard +1/+1
        for grit; net effect: grit +2, resilience -1.
      - Both fighters: travel_comfort +0.5 (more experience traveling
        to events). Stored as REAL (SQLite INTEGER column accepts
        REAL values via NUMERIC affinity — same pattern as
        fighters.consistency in _update_fight_dynamic_fields).

    All changes are SUBTLE (±1 per event) — over a career these
    compound. A 20-fight veteran who's been knocked out 5 times has
    meaningfully higher grit + lower resilience than a fresh
    prospect, even if no single fight produced a dramatic shift.

    After every personality field update, the caller's snapshot
    refresh (already in _process_fight) picks up the new tier.
    """
    is_ko_loss = result_type in ('ko_tko', 'ko', 'tko')

    # ---- travel_comfort: +0.5 for both fighters ----
    # Every fight involves travel (to the venue, to the host city).
    # Over a career, fighters become more comfortable on the road.
    # Stored as REAL (0.5 increments).
    for fid in (a_id, b_id):
        if fid is None:
            continue
        row = conn.execute(
            "SELECT travel_comfort FROM fighter_personality "
            "WHERE fighter_id=?",
            (fid,),
        ).fetchone()
        if not row:
            continue
        cur_tc = row[0] if row[0] is not None else 50
        # Preserve REAL if the current value is REAL (e.g., 50.5).
        if isinstance(cur_tc, float):
            new_tc = float(_clamp_personality(cur_tc + 0.5))
        else:
            # Even if current is INTEGER, +0.5 makes it REAL.
            new_tc = float(_clamp_personality(float(cur_tc) + 0.5))
        conn.execute(
            "UPDATE fighter_personality SET travel_comfort=? "
            "WHERE fighter_id=?",
            (new_tc, fid),
        )

    # ---- winner: ambition shift (satiated OR hungry) ----
    if winner_id is not None and result_type != 'draw':
        # Detect "was champion" — did the winner hold a title before
        # this fight? After the fight, the title state has been
        # updated by _resolve_title_after_fight (runs before publish).
        # The cleanest post-fight signal: is_title_fight AND
        # title_changed → just won the belt (newly satiated).
        # is_title_fight AND NOT title_changed → defended (was
        # champion). Both → satiated → ambition -1.
        was_champion = bool(is_title_fight)
        if was_champion:
            row = conn.execute(
                "SELECT ambition FROM fighter_personality "
                "WHERE fighter_id=?",
                (winner_id,),
            ).fetchone()
            if row:
                cur = row[0] if row[0] is not None else 50
                _set_personality_field(
                    conn, winner_id, "ambition", cur - 1,
                    update_snapshot=False,
                )
        else:
            # Underdog check — winner has lower marketability than
            # loser. The lower-marketed fighter pulling off the win
            # is the canonical "underdog" storyline. If they were
            # evenly matched, no ambition bump (neither underdog nor
            # favorite). (D1.)
            if loser_id is not None:
                w_mkt = conn.execute(
                    "SELECT marketability FROM fighters "
                    "WHERE fighter_id=?",
                    (winner_id,),
                ).fetchone()
                l_mkt = conn.execute(
                    "SELECT marketability FROM fighters "
                    "WHERE fighter_id=?",
                    (loser_id,),
                ).fetchone()
                if (w_mkt and l_mkt
                        and w_mkt[0] is not None
                        and l_mkt[0] is not None
                        and w_mkt[0] < l_mkt[0]):
                    row = conn.execute(
                        "SELECT ambition FROM fighter_personality "
                        "WHERE fighter_id=?",
                        (winner_id,),
                    ).fetchone()
                    if row:
                        cur = row[0] if row[0] is not None else 50
                        _set_personality_field(
                            conn, winner_id, "ambition", cur + 1,
                            update_snapshot=False,
                        )

    # ---- loser: grit + resilience shifts ----
    if loser_id is not None and result_type != 'draw':
        if is_ko_loss:
            # KO loss: grit +2 (real adversity), resilience -1
            # (the chin cracks confidence).
            for field, delta in (("grit", +2), ("resilience", -1)):
                row = conn.execute(
                    f"SELECT {field} FROM fighter_personality "
                    "WHERE fighter_id=?",
                    (loser_id,),
                ).fetchone()
                if row:
                    cur = row[0] if row[0] is not None else 50
                    _set_personality_field(
                        conn, loser_id, field, cur + delta,
                        update_snapshot=False,
                    )
        else:
            # Decision/submission loss: grit +1, resilience +1
            # (bouncing back).
            for field, delta in (("grit", +1), ("resilience", +1)):
                row = conn.execute(
                    f"SELECT {field} FROM fighter_personality "
                    "WHERE fighter_id=?",
                    (loser_id,),
                ).fetchone()
                if row:
                    cur = row[0] if row[0] is not None else 50
                    _set_personality_field(
                        conn, loser_id, field, cur + delta,
                        update_snapshot=False,
                    )


# ----------------------------------------------------------------
# A1 — TITLE_CHANGED subscriber
# ----------------------------------------------------------------

def _process_title_change(conn, event):
    """Subscriber for TITLE_CHANGED.

    New champion: +15 morale (career-defining moment).
    Dethroned champion: -15 morale (lost the belt).

    The TITLE_CHANGED event is published AFTER FIGHT_RESOLVED, so the
    fight-outcome morale change has already been applied. This
    subscriber adds the title-specific boost/penalty on top.

    For a vacant title claim, there is no dethroned champion, so the
    -15 penalty is skipped. We detect this by checking
    titles.title_reigns_count > 1 (a dethronement bumps the count
    past 1; a vacant claim increments it from 0 to 1).
    """
    title_id = event.get('title_id')
    fight_id = event.get('fight_id')
    if fight_id is None:
        return

    # Find the winner + loser of the title fight.
    row = conn.execute(
        "SELECT winner_fighter_id, loser_fighter_id, result_type "
        "FROM fights WHERE fight_id=?",
        (fight_id,),
    ).fetchone()
    if not row:
        return
    winner_id, loser_id, _ = row

    if winner_id is not None:
        m = _get_morale(conn, winner_id)
        _set_morale(conn, winner_id, m + 15, update_snapshot=True)

    if loser_id is not None and title_id is not None:
        # Only apply -15 if this was an actual dethronement (not a
        # vacant title being claimed). title_reigns_count > 1 means
        # the title was held before this fight.
        title_row = conn.execute(
            "SELECT title_reigns_count FROM titles WHERE title_id=?",
            (title_id,),
        ).fetchone()
        if title_row and (title_row[0] or 0) > 1:
            m = _get_morale(conn, loser_id)
            _set_morale(conn, loser_id, m - 15, update_snapshot=True)


# ----------------------------------------------------------------
# A1 + A10 — TICK_ADVANCED subscriber
# ----------------------------------------------------------------

def _process_tick(conn, event):
    """Subscriber for TICK_ADVANCED.

    WEEKLY actions (when current_day is a multiple of 7):
      - Morale drift toward 50 (±1).
      - Ring rust: -2 if fighter hasn't fought in 90+ days.
      - Win-streak bonus: +1 if fighter on 5+ win streak.
      - Injury recovery scan: +5 for each injury that recovered today.
      - Stage5-Final: personality field drift (grit, ambition,
        resilience) for streaks + injury comebacks.

    BIRTHDAY actions (current_date matches a fighter's DOB month/day):
      - injury_proneness: +1 per year of age over 30.
      - weight_cut_difficulty: +1 per year of age over 32.
    """
    current_date = event.get('current_date')
    if not current_date:
        return

    if _is_weekly_tick(conn):
        _weekly_morale_drift(conn, current_date)
        _weekly_personality_drift(conn, current_date)
        _weekly_snapshot_refresh(conn)

    # Birthday aging — checked on every tick (cheap).
    _birthday_aging(conn, current_date)


def _weekly_morale_drift(conn, current_date):
    """Drift every active fighter's morale toward 50 by ±1, apply ring
    rust (-2) for 90+ days without a fight, apply +1 win-streak bonus
    for 5+ win streaks. Also scan for injury recoveries today (+5)."""
    rows = conn.execute(
        "SELECT f.fighter_id, fp.morale, fc.win_streak "
        "FROM fighters f "
        "JOIN fighter_personality fp ON fp.fighter_id=f.fighter_id "
        "LEFT JOIN fighter_career fc ON fc.fighter_id=f.fighter_id "
        "WHERE f.is_active=1 AND f.is_retired=0"
    ).fetchall()

    for fighter_id, morale, ws in rows:
        morale = morale if morale is not None else 50
        ws = ws or 0
        new_morale = morale

        # Drift toward 50 by ±1.
        if morale < MORALE_MEAN:
            new_morale += 1
        elif morale > MORALE_MEAN:
            new_morale -= 1

        # Ring rust — 90+ days since last fight.
        days = _days_since_last_fight(conn, fighter_id, current_date)
        if days is not None and days >= RING_RUST_DAYS:
            new_morale -= 2

        # Win-streak bonus — riding high.
        if ws >= WIN_STREAK_HIGH:
            new_morale += 1

        new_morale = _clamp_morale(new_morale)
        if new_morale != morale:
            conn.execute(
                "UPDATE fighter_personality SET morale=? "
                "WHERE fighter_id=?",
                (new_morale, fighter_id),
            )

    # Injury recovery scan (INJURY_RECOVERED surrogate). The
    # tick_processor._check_injury_recovery function (which runs
    # BEFORE TICK_ADVANCED is published) sets actual_return_date =
    # current_date and is_active=0 for recovered injuries. We pick
    # those up here.
    rec_rows = conn.execute(
        "SELECT fighter_id FROM injuries "
        "WHERE is_active=0 AND actual_return_date=?",
        (current_date,),
    ).fetchall()
    for (rec_fid,) in rec_rows:
        m = _get_morale(conn, rec_fid)
        _set_morale(conn, rec_fid, m + 5, update_snapshot=False)


def _weekly_snapshot_refresh(conn):
    """Refresh descriptor snapshots for all active fighters (batch).

    The weekly drift loop updates morale without refreshing snapshots
    (to avoid N snapshot writes per weekly tick). We refresh them all
    here in one pass so the UI sees the new morale tiers.
    """
    rows = conn.execute(
        "SELECT fighter_id FROM fighters "
        "WHERE is_active=1 AND is_retired=0"
    ).fetchall()
    for (fid,) in rows:
        _refresh_snapshot(conn, fid)


def _weekly_personality_drift(conn, current_date):
    """Stage5-Final — weekly personality field drift.

    Per the brief:
      - Fighter on 3+ loss streak: grit +1, ambition +2 (desperate
        to prove themselves).
      - Fighter on 5+ win streak: ambition -1 (comfortable).
      - Fighter who just returned from injury (detected via
        actual_return_date check): resilience +2, grit +1.

    Mutually exclusive per fighter per tick:
      - A 3+ loss streak + injury recovery in the same week is
        possible — both fire (the fighter is doubly tested). The
        resilience +2 (comeback) and grit +1 (loss streak) compound.
      - A 5+ win streak + injury recovery is rare (winning fighters
        don't usually get injured) but if it happens, the win streak
        comfort (-1 ambition) and the comeback resilience (+2) both
        fire — the fighter is "comfortably on top, just got healthy".

    All updates use _set_personality_field with update_snapshot=False
    (the caller's _weekly_snapshot_refresh handles the snapshot write
    in one batched pass).
    """
    # ---- streak-based grit + ambition shifts ----
    rows = conn.execute(
        "SELECT f.fighter_id, fc.win_streak, fc.loss_streak, "
        "fp.grit, fp.ambition "
        "FROM fighters f "
        "JOIN fighter_personality fp ON fp.fighter_id=f.fighter_id "
        "LEFT JOIN fighter_career fc ON fc.fighter_id=f.fighter_id "
        "WHERE f.is_active=1 AND f.is_retired=0"
    ).fetchall()
    for fighter_id, ws, ls, cur_grit, cur_amb in rows:
        ws = ws or 0
        ls = ls or 0
        cur_grit = cur_grit if cur_grit is not None else 50
        cur_amb = cur_amb if cur_amb is not None else 50
        if ls >= LOSS_STREAK_GRIT_ONSET:
            # Desperate to prove themselves.
            _set_personality_field(
                conn, fighter_id, "grit", cur_grit + 1,
                update_snapshot=False,
            )
            _set_personality_field(
                conn, fighter_id, "ambition", cur_amb + 2,
                update_snapshot=False,
            )
        elif ws >= WIN_STREAK_COMFORT_ONSET:
            # Comfortable — riding high.
            _set_personality_field(
                conn, fighter_id, "ambition", cur_amb - 1,
                update_snapshot=False,
            )

    # ---- injury comeback: resilience +2, grit +1 ----
    # Same detection pattern as _weekly_morale_drift's injury scan
    # — injuries with is_active=0 AND actual_return_date == current_
    # date were just recovered by tick_processor._check_injury_
    # recovery (which runs BEFORE TICK_ADVANCED is published).
    rec_rows = conn.execute(
        "SELECT DISTINCT fighter_id FROM injuries "
        "WHERE is_active=0 AND actual_return_date=?",
        (current_date,),
    ).fetchall()
    for (rec_fid,) in rec_rows:
        row = conn.execute(
            "SELECT grit, resilience FROM fighter_personality "
            "WHERE fighter_id=?",
            (rec_fid,),
        ).fetchone()
        if not row:
            continue
        cur_grit, cur_res = row
        cur_grit = cur_grit if cur_grit is not None else 50
        cur_res = cur_res if cur_res is not None else 50
        _set_personality_field(
            conn, rec_fid, "resilience", cur_res + 2,
            update_snapshot=False,
        )
        _set_personality_field(
            conn, rec_fid, "grit", cur_grit + 1,
            update_snapshot=False,
        )


def _birthday_aging(conn, current_date):
    """On a fighter's birthday, age up injury_proneness and
    weight_cut_difficulty per the brief."""
    try:
        dt = datetime.strptime(current_date, "%Y-%m-%d")
    except (ValueError, TypeError):
        return

    rows = conn.execute(
        "SELECT fighter_id, date_of_birth, injury_proneness, "
        "weight_cut_difficulty FROM fighters "
        "WHERE is_active=1 AND is_retired=0 "
        "AND date_of_birth IS NOT NULL"
    ).fetchall()

    for fighter_id, dob, cur_pron, cur_wcd in rows:
        if not dob:
            continue
        try:
            dob_dt = datetime.strptime(dob, "%Y-%m-%d")
        except (ValueError, TypeError):
            continue

        # Birthday match (month + day).
        if dob_dt.month != dt.month or dob_dt.day != dt.day:
            continue

        # Compute age. Today IS the birthday so the year-only diff
        # is correct, but be defensive.
        age = dt.year - dob_dt.year
        if (dt.month, dt.day) < (dob_dt.month, dob_dt.day):
            age -= 1

        cur_pron = cur_pron if cur_pron is not None else 50
        cur_wcd = cur_wcd if cur_wcd is not None else 50
        updates = {}
        if age > INJURY_PRONENESS_AGE_THRESHOLD:
            new_pron = min(100, cur_pron + 1)
            if new_pron != cur_pron:
                updates['injury_proneness'] = new_pron
        if age > WEIGHT_CUT_DIFFICULTY_AGE_THRESHOLD:
            new_wcd = min(100, cur_wcd + 1)
            if new_wcd != cur_wcd:
                updates['weight_cut_difficulty'] = new_wcd
        if updates:
            set_clause = ", ".join(f"{k}=?" for k in updates)
            params = list(updates.values()) + [fighter_id]
            conn.execute(
                f"UPDATE fighters SET {set_clause}, "
                "updated_at=CURRENT_TIMESTAMP WHERE fighter_id=?",
                params,
            )
            _refresh_snapshot(conn, fighter_id)


# ----------------------------------------------------------------
# A1 — CAMP_COMPLETED / CAMP_INJURY / FIGHT_CANCELLED subscribers
# ----------------------------------------------------------------

def _process_camp_completed(conn, event):
    """Subscriber for CAMP_COMPLETED. +3 morale (training went well)."""
    fighter_id = event.get('fighter_id')
    if fighter_id is None:
        return
    m = _get_morale(conn, fighter_id)
    _set_morale(conn, fighter_id, m + 3, update_snapshot=True)


def _process_camp_injury(conn, event):
    """Subscriber for CAMP_INJURY. -5 morale (training setback)."""
    fighter_id = event.get('fighter_id')
    if fighter_id is None:
        return
    m = _get_morale(conn, fighter_id)
    _set_morale(conn, fighter_id, m - 5, update_snapshot=True)


def _process_fight_cancelled(conn, event):
    """Subscriber for FIGHT_CANCELLED (weight cut miss).

    Fighter who missed weight: -5 morale.
    Opponent: -3 morale (frustration).

    NOTE: FIGHT_CANCELLED is not yet published by app.py (the weight
    cut cancellation path returns early before the FIGHT_RESOLVED
    publish). Phase A5 will wire news coverage and publish the event.
    This subscriber is registered now for forward-compat.
    """
    missed_fighter_id = event.get('missed_fighter_id')
    opponent_id = event.get('opponent_id')
    if missed_fighter_id is not None:
        m = _get_morale(conn, missed_fighter_id)
        _set_morale(conn, missed_fighter_id, m - 5, update_snapshot=True)
    if opponent_id is not None:
        m = _get_morale(conn, opponent_id)
        _set_morale(conn, opponent_id, m - 3, update_snapshot=True)


# ----------------------------------------------------------------
# Registration
# ----------------------------------------------------------------

def register_subscribers():
    """Register all morale + dynamic-fields subscribers on the event bus.

    Call once at startup (UI App.__init__, test setup, etc.). The
    function is safe to call multiple times — the event bus's
    subscribe() simply appends to its subscriber list. For test
    isolation, call reset_bus() first to clear any prior registrations.

    Subscribes to:
      FIGHT_RESOLVED  → _process_fight
      TITLE_CHANGED   → _process_title_change
      TICK_ADVANCED   → _process_tick
      CAMP_COMPLETED  → _process_camp_completed
      CAMP_INJURY     → _process_camp_injury
      FIGHT_CANCELLED → _process_fight_cancelled
    """
    from event_bus import get_bus, Events
    bus = get_bus()
    bus.subscribe(
        Events.FIGHT_RESOLVED, _process_fight,
        name="morale.process_fight",
    )
    bus.subscribe(
        Events.TITLE_CHANGED, _process_title_change,
        name="morale.process_title_change",
    )
    bus.subscribe(
        Events.TICK_ADVANCED, _process_tick,
        name="morale.process_tick",
    )
    bus.subscribe(
        Events.CAMP_COMPLETED, _process_camp_completed,
        name="morale.process_camp_completed",
    )
    bus.subscribe(
        Events.CAMP_INJURY, _process_camp_injury,
        name="morale.process_camp_injury",
    )
    bus.subscribe(
        Events.FIGHT_CANCELLED, _process_fight_cancelled,
        name="morale.process_fight_cancelled",
    )
