"""CAGE EMPIRE Save/Load System (Stage 5 — Task ID Stage5-SaveLoad).

This module wires the save/load functionality. The game currently has
NO save/load — the DB IS the game state. Saving = backing up the DB
file to data/saves/{name}.db; loading = copying that file back to the
active DB path. This is fast (the DB is ~25MB) and preserves the
exact state (every table, every row, every column — no serialization
loss).

CONVENTIONS compliance:
  §5  — One table-group per task. This task adds NO new tables — the
        DB IS the save state. Per the brief: "Do NOT add new tables
        — the DB IS the save state." All save/load metadata lives
        as JSON files alongside the .db files (one .json per save).
  §6  — Smoke test protocol followed. The acceptance test rebuilds
        the DB, seeds, then exercises save/load.
  §10 — Dynamic-version pattern. The acceptance test reads
        build_db.CODE_SCHEMA_VERSION at test time (no hardcoded
        '3.6.0' string). This module also writes the schema_version
        into the save metadata at save time (queried from
        schema_meta, not hardcoded).
  §13 — Design Law: Investment pillar (the player's progress — the
        fighters they scouted, the champions they crowned, the
        market heat they built — is preserved across save/load.
        Without save/load, every game session is ephemeral; with
        it, the player's empire is durable. The "remember that
        championship reign" storyline only matters if the player
        can come back to it tomorrow. This is the foundation of
        the Historian fantasy: "The world remembers what I built"
        — the player must first be able to RETURN to what they
        built.)
  §14 — Voice Layer: save/load is internal (file names, metadata
        JSON). Raw numbers ARE allowed in the JSON metadata per
        the brief ("save/load is internal (file names, metadata),
        so raw numbers are OK in the JSON metadata"). No
        player-facing text is generated by this module.
  §15 — Event Bus: auto_save subscribes to TICK_ADVANCED. No new
        inline side effects in run_tick. The auto-save fires as a
        downstream subscriber, SILENTLY (no news item, no print —
        background operation per the brief).

SAVE METADATA JSON format:
  {
      "save_name": "my_save",
      "timestamp": "2026-07-23T18:30:00",
      "sim_date": "2026-08-15",
      "promotion_name": "Alpha Combat Federation",
      "current_cash": 45000000,
      "fighter_count": 4000,
      "event_count": 25,
      "schema_version": "3.6.0"
  }

AUTO-SAVE:
  - Cadence: every 30 sim days (monthly). The cadence check uses
    simulation_clock.current_day (the value AFTER run_tick's clock
    advance — so day 30, 60, 90, ... trigger an auto-save).
  - File naming: `autosave_<sim_date>_<wallclock>.db` — the sim_date
    is human-readable (what sim day was this?), the wall-clock
    timestamp guarantees uniqueness (avoids overwriting if multiple
    auto-saves fire on the same sim day via the "steps" parameter).
  - Rotation: keeps only the last 3 auto-saves (by mtime). Older
    auto-saves are deleted (both .db and .json). The "rotating"
    pattern means the player always has 3 recent restore points.
  - SILENT: no news item, no print to stdout (errors print to
    stderr — defensive, auto-save should never crash the game).

USAGE:
  from save_load import (save_game, load_game, list_saves,
      delete_save, auto_save, register_subscribers)

  # Manual save
  save_game(conn, save_name="my_save")
  # → writes data/saves/my_save.db + data/saves/my_save.json

  # Manual save with auto-generated name (timestamp)
  save_game(conn)
  # → writes data/saves/save_<YYYYMMDD_HHMMSS>.db

  # List saves
  saves = list_saves()
  # → [{"name": "my_save", "timestamp": ..., "sim_date": ..., ...}, ...]

  # Load
  new_conn = load_game("my_save")
  # → copies data/saves/my_save.db back to data/cage_empire.db,
  #   returns a fresh sqlite3.Connection

  # Delete
  delete_save("my_save")
  # → removes data/saves/my_save.db + .json

  # Auto-save (registered automatically via register_subscribers)
  register_subscribers()
  # → on every TICK_ADVANCED, auto_save fires; monthly ticks
  #   trigger a rotating auto-save to data/saves/autosave_*.db

DESIGN DECISIONS:
  - shutil.copy2 (NOT database dumps). The brief mandates this —
    the DB is small (~25MB), and a file copy preserves the EXACT
    state (every table, every row, every column, including
    sqlite_sequence auto-increment counters). A dump + reload would
    lose AUTOINCREMENT counters and could reorder rows. File copy
    is byte-for-byte identical. (D1.)
  - conn.commit() BEFORE shutil.copy2. This flushes any pending
    transaction (e.g., run_tick's clock advance + retirements +
    contract expiries + injury recoveries + training camps + scouting
    reports) to the file BEFORE the copy. Without this, an auto-save
    fired by the TICK_ADVANCED subscriber would capture the PRE-tick
    state (because run_tick commits AFTER bus.publish). With it,
    the auto-save captures the post-tick state. The subsequent
    conn.commit() in run_tick is a no-op (no pending transaction).
    (D2.)
  - Auto-save file naming uses BOTH sim_date AND wall-clock
    timestamp. sim_date alone could collide if the player advances
    multiple months via the "steps" parameter in a single run_tick
    call (each month's TICK_ADVANCED fires within microseconds).
    Wall-clock timestamp guarantees uniqueness. The sim_date prefix
    makes the file human-readable ("autosave_2026-09-15_*.db" tells
    the player when in the SIM this save was made). (D3.)
  - Save name sanitization: only [a-zA-Z0-9_-] allowed. Disallowed
    chars (spaces, slashes, dots, etc.) are replaced with '_'. This
    prevents path traversal (../etc/passwd) and weird filesystem
    behavior. The brief mandates "no spaces, no special chars".
    (D4.)
  - list_saves() reads metadata from .json files, NOT from the .db
    files. This is fast (no DB connections opened) and works even
    if the .db file is corrupted (the metadata is preserved). The
    .json file is the source of truth for save metadata.
  - load_game() overwrites the active DB path. The caller is
    responsible for closing any existing connection BEFORE calling
    load_game — on Windows, you can't overwrite a file that's open
    by another process. The function returns a NEW connection to
    the restored DB. (D5.)
  - Auto-save is SILENT. Per the brief: "Auto-save should be SILENT
    (no news item, no print) — it's a background operation." Errors
    print to stderr (defensive — a broken auto-save shouldn't crash
    the game, but the operator should know it failed).
  - auto_save signature is (conn, event) per the event bus
    subscriber convention (every subscriber takes (conn, event)).
    The brief writes "auto_save(conn)" as shorthand — the event
    payload is used to extract the sim_date for the filename.
    (D6.)
"""

import json
import re
import shutil
import sqlite3
import sys
import os
from datetime import datetime
from pathlib import Path


# ----------------------------------------------------------------
# Paths + constants
# ----------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent
PROJECT_DIR = BASE_DIR.parent
DATA_DIR = PROJECT_DIR / "data"
# DB_PATH can be overridden via CAGE_EMPIRE_DB_PATH env var.
# Tests use data/cage_empire_test.db to avoid destroying the world DB.
_DEFAULT_DB_PATH = DATA_DIR / "cage_empire.db"
DB_PATH = Path(os.environ.get("CAGE_EMPIRE_DB_PATH", str(_DEFAULT_DB_PATH)))
SAVES_DIR = DATA_DIR / "saves"

# Auto-save configuration.
# AUTOSAVE_PREFIX: filenames start with this — list_saves uses it
# to tag saves as "is_autosave: True" and _prune_autosaves uses it
# to find auto-save files to rotate.
AUTOSAVE_PREFIX = "autosave_"

# AUTOSAVE_MAX_FILES: keep only the last N auto-saves (by mtime).
# Per the brief: "Keeps only the last 3 auto-saves (rotating)."
AUTOSAVE_MAX_FILES = 3

# AUTOSAVE_CADENCE_DAYS: auto-save fires every N sim days. Per the
# brief: "Saves every 30 days (monthly auto-save)."
AUTOSAVE_CADENCE_DAYS = 30

# PLAYER_PROMOTION_ID: the player's promotion (promotion_id=1 —
# Alpha Combat in the small seed; first promotion by AUTOINCREMENT
# in the world seed). Used to query the promotion_name + current_
# cash for save metadata.
PLAYER_PROMOTION_ID = 1

# Save name sanitization pattern. Allow letters, digits, underscore,
# hyphen. Everything else is replaced with '_'. Disallow leading
# dots (hidden files on Unix) and path separators.
_SAVE_NAME_SAFE_RE = re.compile(r"[^a-zA-Z0-9_-]")

# Max save name length (after sanitization). 100 is generous — the
# filesystem allows 255, but we leave headroom for the .db + .json
# extensions and the autosave_ prefix.
_MAX_SAVE_NAME_LEN = 100


# ----------------------------------------------------------------
# Internal helpers
# ----------------------------------------------------------------

def _ensure_saves_dir():
    """Create data/saves/ if it doesn't exist.

    Idempotent — mkdir(parents=True, exist_ok=True) is a no-op if
    the directory already exists. The directory is in .gitignore
    (line 35 of .gitignore: `data/saves/`), so saves are NEVER
    committed to the repo.
    """
    SAVES_DIR.mkdir(parents=True, exist_ok=True)


def _sanitize_save_name(save_name):
    """Sanitize a save name — only [a-zA-Z0-9_-] allowed.

    Per the brief: "The save file name should be safe (no spaces,
    no special chars)." This function enforces that:
      - Strips leading/trailing whitespace.
      - Replaces any char that's not [a-zA-Z0-9_-] with '_'.
      - Truncates to _MAX_SAVE_NAME_LEN chars.
      - Falls back to "save" if the result is empty.

    Args:
        save_name: raw user-provided name (or None).

    Returns:
        Sanitized name (str). Always non-empty.
    """
    if save_name is None:
        return "save"
    name = str(save_name).strip()
    if not name:
        return "save"
    name = _SAVE_NAME_SAFE_RE.sub("_", name)
    # Strip leading underscores (caused by leading special chars)
    # to keep the name readable.
    name = name.lstrip("_")
    if not name:
        return "save"
    # Truncate to max length.
    if len(name) > _MAX_SAVE_NAME_LEN:
        name = name[:_MAX_SAVE_NAME_LEN]
    return name


def _query_save_metadata(conn):
    """Query the DB for save metadata fields.

    Per the brief: "query the DB for: simulation_clock.current_date,
    promotions.name + current_cash (for promotion_id=1), COUNT(*)
    FROM fighters, COUNT(*) FROM events." The schema_version is
    also queried from schema_meta (per the brief's metadata JSON
    example).

    Defensive — each query is wrapped in try/except so a missing
    table (e.g., a partial DB) doesn't crash the save. This is
    important because save_game may be called on a DB that's mid-
    migration or partially built.

    Args:
        conn: sqlite3 connection.

    Returns:
        Dict with keys: sim_date, promotion_name, current_cash,
        fighter_count, event_count, schema_version. Missing values
        default to None / 0 / "unknown".
    """
    meta = {
        "sim_date": None,
        "promotion_name": "Unknown",
        "current_cash": 0,
        "fighter_count": 0,
        "event_count": 0,
        "schema_version": "unknown",
    }

    # sim_date — simulation_clock.current_date (qualified per
    # Task 14.7 to avoid the bare-current_date SQLite quirk).
    try:
        row = conn.execute(
            "SELECT simulation_clock.current_date "
            "FROM simulation_clock WHERE clock_id=1"
        ).fetchone()
        if row and row[0]:
            meta["sim_date"] = row[0]
    except sqlite3.Error:
        pass

    # promotion_name + current_cash for the player's promotion.
    try:
        row = conn.execute(
            "SELECT name, current_cash FROM promotions WHERE promotion_id=?",
            (PLAYER_PROMOTION_ID,),
        ).fetchone()
        if row:
            if row[0]:
                meta["promotion_name"] = row[0]
            meta["current_cash"] = row[1] if row[1] is not None else 0
    except sqlite3.Error:
        pass

    # fighter_count.
    try:
        row = conn.execute("SELECT COUNT(*) FROM fighters").fetchone()
        if row:
            meta["fighter_count"] = row[0]
    except sqlite3.Error:
        pass

    # event_count.
    try:
        row = conn.execute("SELECT COUNT(*) FROM events").fetchone()
        if row:
            meta["event_count"] = row[0]
    except sqlite3.Error:
        pass

    # schema_version — from schema_meta (the canonical version
    # recorded by build_db.py on every fresh + migrate build).
    try:
        row = conn.execute(
            "SELECT schema_version FROM schema_meta "
            "WHERE schema_name='cage_empire'"
        ).fetchone()
        if row and row[0]:
            meta["schema_version"] = row[0]
    except sqlite3.Error:
        pass

    return meta


def _write_metadata(save_name, conn):
    """Build + write the save metadata JSON.

    The JSON file lives at data/saves/{save_name}.json (alongside
    the .db file). Per the brief's metadata JSON format example.

    Args:
        save_name: sanitized save name (used for the filename).
        conn: sqlite3 connection (for querying sim state).
    """
    meta_path = SAVES_DIR / f"{save_name}.json"
    metadata = {
        "save_name": save_name,
        "timestamp": datetime.now().isoformat(timespec="seconds"),
    }
    metadata.update(_query_save_metadata(conn))
    with open(meta_path, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=4, default=str)
    return metadata


def _prune_autosaves():
    """Keep only the last N auto-saves (by mtime).

    Per the brief: "Keeps only the last 3 auto-saves (rotating)."
    Lists all files matching `autosave_*.db`, sorts by mtime DESC,
    and deletes all but the newest AUTOSAVE_MAX_FILES. Both the
    .db and .json files are deleted for pruned saves.

    Silent — pruning errors are swallowed (a stuck file shouldn't
    crash the auto-save path).
    """
    autosave_files = list(SAVES_DIR.glob(f"{AUTOSAVE_PREFIX}*.db"))
    if len(autosave_files) <= AUTOSAVE_MAX_FILES:
        return

    # Sort by mtime DESC (newest first).
    autosave_files.sort(key=lambda p: p.stat().st_mtime, reverse=True)

    # Delete all but the newest N.
    for old_db_path in autosave_files[AUTOSAVE_MAX_FILES:]:
        try:
            old_db_path.unlink()
        except OSError:
            pass
        # Also delete the matching .json metadata file.
        old_json_path = old_db_path.with_suffix(".json")
        if old_json_path.exists():
            try:
                old_json_path.unlink()
            except OSError:
                pass


# ----------------------------------------------------------------
# Public API
# ----------------------------------------------------------------

def save_game(conn, save_name=None):
    """Save the current DB to data/saves/{save_name}.db.

    Copies the active DB file to data/saves/{save_name}.db using
    shutil.copy2 (byte-for-byte copy preserving metadata). Also
    writes a save metadata JSON file alongside the .db file with
    the sim state at save time.

    Args:
        conn: sqlite3 connection to the active DB. Used for two
            purposes: (1) conn.commit() to flush any pending
            transaction before the copy (so the file has the
            latest state — critical when auto_save fires as a
            TICK_ADVANCED subscriber before run_tick's final
            commit); (2) querying the save metadata fields
            (sim_date, promotion_name, current_cash, fighter_count,
            event_count, schema_version).
        save_name: name for the save file. If None, uses a
            timestamp-based name (save_YYYYMMDD_HHMMSS). The name
            is sanitized per _sanitize_save_name — only [a-zA-Z0-9_-]
            allowed, disallowed chars replaced with '_'.

    Returns:
        The sanitized save_name (str). Useful when save_name=None
        — the caller can learn what name was assigned.

    Raises:
        sqlite3.Error: if the DB connection is broken (the commit
            or metadata queries fail with a non-recoverable error).
        OSError: if the file copy fails (e.g., disk full, permission
            denied).
    """
    _ensure_saves_dir()

    # Generate save name if not provided.
    if save_name is None:
        save_name = datetime.now().strftime("save_%Y%m%d_%H%M%S")

    save_name = _sanitize_save_name(save_name)

    # Commit any pending transactions so the file copy has the
    # latest state. CRITICAL when auto_save fires as a TICK_ADVANCED
    # subscriber — run_tick commits AFTER bus.publish, so without
    # this commit, the auto-save would capture the PRE-tick state
    # (D2). The subsequent conn.commit() in run_tick is a no-op.
    try:
        conn.commit()
    except sqlite3.Error:
        # A broken commit shouldn't crash save_game — the file
        # copy may still succeed (the journal may have the data
        # even if commit failed). Worst case, the save is stale.
        pass

    save_db_path = SAVES_DIR / f"{save_name}.db"

    # Copy the DB file (per the brief: shutil.copy2, NOT database
    # dumps). shutil.copy2 preserves file metadata (mtime, mode).
    shutil.copy2(DB_PATH, save_db_path)

    # Build + write metadata JSON.
    _write_metadata(save_name, conn)

    return save_name


def load_game(save_name):
    """Load data/saves/{save_name}.db back to the active DB path.

    Copies the save file back to DB_PATH (data/cage_empire.db),
    overwriting the current DB. Returns a NEW sqlite3.Connection
    to the restored DB. The caller is responsible for closing any
    existing connection BEFORE calling load_game — on Windows,
    you can't overwrite a file that's open by another process.

    Args:
        save_name: name of the save to load. Sanitized per
            _sanitize_save_name.

    Returns:
        sqlite3.Connection — a fresh connection to the restored DB,
        with PRAGMA foreign_keys = ON (matching the convention used
        by App.__init__ and tick_processor.main).

    Raises:
        FileNotFoundError: if the save file doesn't exist.
        OSError: if the file copy fails.
    """
    _ensure_saves_dir()

    save_name = _sanitize_save_name(save_name)
    save_db_path = SAVES_DIR / f"{save_name}.db"

    if not save_db_path.exists():
        raise FileNotFoundError(
            f"Save file not found: {save_db_path} (save_name={save_name!r})"
        )

    # Copy the save file back to the active DB path. shutil.copy2
    # preserves file metadata (mtime, mode). The active DB file is
    # overwritten in place.
    shutil.copy2(save_db_path, DB_PATH)

    # Open a new connection to the restored DB. The caller is
    # responsible for closing any prior connection (we cannot do
    # it from here — we don't have a reference to it).
    conn = sqlite3.connect(DB_PATH)
    conn.execute("PRAGMA foreign_keys = ON;")
    return conn


def list_saves():
    """Return a list of save metadata dicts.

    Iterates over all .json files in data/saves/, reads each one,
    and returns a list of metadata dicts. Sorted by timestamp DESC
    (newest first) so the UI can display the most recent saves at
    the top.

    Returns:
        List of dicts, each with keys:
            name (str):          save_name (sanitized).
            timestamp (str|None): ISO timestamp of the save.
            sim_date (str|None):  simulation_clock.current_date at save.
            promotion (str):      promotions.name for promotion_id=1.
            cash (float|int):     promotions.current_cash for promotion_id=1.
            fighters (int):       COUNT(*) FROM fighters.
            events (int):         COUNT(*) FROM events.
            schema_version (str): schema_meta.schema_version.
            is_autosave (bool):   True if name starts with AUTOSAVE_PREFIX.
            db_path (str):        absolute path to the .db file.
    """
    _ensure_saves_dir()

    saves = []
    for json_path in SAVES_DIR.glob("*.json"):
        try:
            with open(json_path, "r", encoding="utf-8") as f:
                meta = json.load(f)
        except (json.JSONDecodeError, OSError):
            # Skip corrupted JSON — the .db file may still be
            # valid, but we can't display metadata without the
            # JSON. The UI can fall back to showing the filename.
            continue

        name = meta.get("save_name", json_path.stem)
        saves.append({
            "name": name,
            "timestamp": meta.get("timestamp"),
            "sim_date": meta.get("sim_date"),
            "promotion": meta.get("promotion_name"),
            "cash": meta.get("current_cash"),
            "fighters": meta.get("fighter_count"),
            "events": meta.get("event_count"),
            "schema_version": meta.get("schema_version"),
            "is_autosave": name.startswith(AUTOSAVE_PREFIX),
            "db_path": str(SAVES_DIR / f"{name}.db"),
        })

    # Sort by timestamp DESC (newest first). Missing timestamps
    # sort to the end (treated as empty string).
    saves.sort(key=lambda s: s.get("timestamp") or "", reverse=True)
    return saves


def delete_save(save_name):
    """Delete a save file (both .db and .json).

    Args:
        save_name: name of the save to delete. Sanitized per
            _sanitize_save_name.

    Returns:
        True if any file was deleted (the .db OR .json), False if
        no save with that name existed.
    """
    save_name = _sanitize_save_name(save_name)
    save_db_path = SAVES_DIR / f"{save_name}.db"
    save_json_path = SAVES_DIR / f"{save_name}.json"

    deleted = False
    if save_db_path.exists():
        try:
            save_db_path.unlink()
            deleted = True
        except OSError:
            pass
    if save_json_path.exists():
        try:
            save_json_path.unlink()
            deleted = True
        except OSError:
            pass
    return deleted


# ----------------------------------------------------------------
# Event bus subscriber (auto-save)
# ----------------------------------------------------------------

def auto_save(conn, event):
    """TICK_ADVANCED subscriber — saves every 30 sim days (monthly).

    The cadence check reads simulation_clock.current_day from the
    DB (the value AFTER run_tick's clock advance — so day 30, 60,
    90, ... trigger an auto-save). If the cadence matches, calls
    save_game with an auto-generated name and prunes old auto-saves.

    SILENT — per the brief: "Auto-save should be SILENT (no news
    item, no print) — it's a background operation." Errors print to
    stderr (defensive — a broken auto-save shouldn't crash the
    game, but the operator should know it failed).

    Args:
        conn: sqlite3 connection (passed by the event bus).
        event: dict with at least 'type' = Events.TICK_ADVANCED and
            'current_date' (ISO date string of the new sim date).
            The current_date is used in the auto-save filename for
            human-readability — the file is named
            `autosave_<sim_date>_<wallclock>.db`.
    """
    # Cadence check — only save on every 30th sim day. Read
    # current_day from the DB (NOT from the event payload — the
    # TICK_ADVANCED event doesn't carry current_day, only
    # current_date). The DB has the NEW current_day because run_tick
    # updates the clock BEFORE bus.publish.
    try:
        row = conn.execute(
            "SELECT simulation_clock.current_day "
            "FROM simulation_clock WHERE clock_id=1"
        ).fetchone()
        if not row:
            return
        current_day = row[0]
    except sqlite3.Error:
        return

    if current_day % AUTOSAVE_CADENCE_DAYS != 0:
        return

    # Build the auto-save name. sim_date (from the event payload)
    # is human-readable ("when in the sim was this?"). Wall-clock
    # timestamp guarantees uniqueness (avoids overwriting if
    # multiple auto-saves fire on the same sim day via the "steps"
    # parameter). (D3.)
    sim_date = "unknown"
    if isinstance(event, dict):
        sim_date = event.get("current_date", "unknown") or "unknown"
    # Sanitize sim_date for use in a filename (replace dashes with
    # underscores — dashes are allowed in save names, but we want
    # the auto-save name to be one token without internal structure
    # ambiguity). Actually, dashes ARE allowed per _sanitize_save_name,
    # so we just need to replace any ':' or other disallowed chars.
    # ISO date strings (YYYY-MM-DD) are already safe.
    safe_sim_date = _sanitize_save_name(sim_date)
    wallclock = datetime.now().strftime("%Y%m%d_%H%M%S")
    save_name = f"{AUTOSAVE_PREFIX}{safe_sim_date}_{wallclock}"

    try:
        save_game(conn, save_name=save_name)
        _prune_autosaves()
    except Exception as e:
        # SILENT — auto-save is a background operation. Log to
        # stderr so the operator can see if something broke, but
        # do NOT raise (a broken auto-save shouldn't crash the
        # game or block other TICK_ADVANCED subscribers).
        print(f"Warning: auto_save failed: {type(e).__name__}: {e}",
              file=sys.stderr)


# ----------------------------------------------------------------
# Registration
# ----------------------------------------------------------------

def register_subscribers():
    """Register the auto_save subscriber on the global event bus.

    Call once at startup (UI App.__init__, test setup, etc.). Safe
    to call multiple times — the event bus's subscribe() simply
    appends to its subscriber list. For test isolation, call
    reset_bus() first to clear any prior registrations.

    Subscribes to:
      TICK_ADVANCED → auto_save (monthly cadence check + rotating
                                  file pruning)
    """
    from event_bus import get_bus, Events
    bus = get_bus()
    bus.subscribe(
        Events.TICK_ADVANCED, auto_save,
        name="save_load.auto_save",
    )
